### PR TITLE
Add windows tests to circleci config

### PR DESCRIPTION
**Pull request by Kronopt**

### CODE REVIEW

**Comment by Naramsim** [comment]
@Kronopt is the below image normal or just a Github glitch? I saw that on CircleCI all the tests passed.


circle

**Comment by Kronopt** [comment]
I think it has something to do with the settings of this repo.
I changed the name of the circleci jobs, so the jobs he's waiting for no longer exist.

Is that something you can change, @Naramsim?
Or should I just change the names back?
Still, I added a new job that should be added to this list of expected jobs

**Comment by Naramsim** [comment]
Is it possible @Kronopt to add also a py27-win?

**Comment by Naramsim** [comment]
It's up to you. If you have time and want to try your welcome to do it, but it's not necessary :)

Sometimes dealing with CI systems can be a pain in the neck, so feel free to let the things how they are now.

**Pull request merged**
